### ISSUE TITLE
Using an external DB doesnt work

### ISSUE THREAD

**Issue by Pflegusch** [jptissot/matomo-chart#6]
When I try to connect to an external DB, I get an access denied error because there are `&#039;` (') characters being passed to the login. `Access denied for user &#039;db-user&#039;@&#039;db-address&#039;` I tried passing the values directly in the deployment.yaml but it still doesn't work, do you guys have a quick fix or an explanation for this? Using Helm version 3.2.0-rc.1. Any help would be appreciated :)

**Comment by jptissot** [comment]
Any thoughts @YKWeyer ?

**Comment by YKWeyer** [comment]
Hum I didn't try the Helm3 version of the chart so far, but I am curious about this issue :smiley: 

@Pflegusch Did you include those single-quotes in your `values.yaml`? How does the `env:` section of your generated `deployment.yaml` look like? (I'm interested in the `MATOMO_DATABASE_USER` / `MARIADB_HOST` variables)

Which version of the Bitnami container are you using? From the look of it, and since you mentioned having tried to hardcode the username and address in your deployment, my first suspect would be the init script in the container, but then it would affect all installations, not just the ones using on an external database :thinking:
